name: Build PDF Studio APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flet

      - name: Build APK
        run: |
          yes | flet build apk \
            --build-number 1 \
            --verbose
        env:
          PIP_ONLY_BINARY: ":all:"
          PIP_EXTRA_INDEX_URL: "https://pypi.flet.dev"
          PIP_TARGET: "/home/runner/work/PDF-Studio/PDF-Studio/build/site-packages/arm64-v8a"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: PDF-Studio-APK
          path: build/apk/*.apk
